apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@example.com

    privateKeySecretRef:
      name: example-cloudflare-issuer-key

    solvers:
      - selector: {}
        dns01:
          cloudflare:
            email: me@example.com
            apiTokenSecretRef:
              name: example-cloudflare-api
              key: key

