apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  labels:
    app.kubernetes.io/name: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: photoprism
  template:
    metadata:
      labels:
        app.kubernetes.io/name: photoprism
    spec:
      containers:
      - name: "photoprism"
        image: "photoprism:latest"
        imagePullPolicy: "Always"
        env:
        - {name: "PHOTOPRISM_ADMIN_USER", value: "admin"}
        - {name: "PHOTOPRISM_AUTH_MODE", value: "password"}
        #- {name: "PHOTOPRISM_SITE_URL", value: "http://localhost:2342/"}
        - {name: "PHOTOPRISM_WORKERS", value: "2"}
        - {name: "PHOTOPRISM_DISABLE_CHOWN", value: "false"}
        - {name: "PHOTOPRISM_DISABLE_TENSORFLOW", value: "false"}
        - {name: "PHOTOPRISM_DATABASE_DRIVER", value: "sqlite"}
        # environment for a DBMS server
        #- {name: "PHOTOPRISM_DATABASE_DRIVER", value: "mysql"}
        #- {name: "PHOTOPRISM_DATABASE_SERVER", value: "mariadb:3306"}
        #- {name: "PHOTOPRISM_DATABASE_NAME", value: "photoprism"}
        #- {name: "PHOTOPRISM_DATABASE_USER", value: "photoprism"}
        #- {name: "PHOTOPRISM_DATABASE_PASSWORD", value: "insecure"}
        # Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
        - {name: "PHOTOPRISM_INIT", value: "update clean"}
        # Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
        #- {name: "PHOTOPRISM_UID", value: "1000"}
        #- {name: "PHOTOPRISM_GID", value: "1000"}
        # load secrets (admin & database passwords) as env
        envFrom:
        - secretRef:
            name: photoprism-secret-env
        ports:
        - name: http
          containerPort: 2342
          protocol: TCP
        volumeMounts:
        - mountPath: /photoprism/originals
          name: photoprism-originals
        - mountPath: /photoprism/storage
          name: photoprism-storage
      volumes:
      - name: photoprism-originals
        persistentVolumeClaim:
          claimName: photoprism-originals
      - name: photoprism-storage
        persistentVolumeClaim:
          claimName: photoprism-storage

