apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml

transformers:
  - transform-syncthing-image-tags.yaml
  - transform-syncthing-labels.yaml

