apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/name: syncthing
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate  
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
    spec:
      containers:
      - image: syncthing/syncthing
        name: syncthing
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000
        ports:
        - name: web-ui
          containerPort: 8384
        - name: syncthing-tcp
          containerPort: 22000
          protocol: TCP
        - name: syncthing-udp
          containerPort: 22000
          protocol: UDP
        - name: syncthing-dsc
          containerPort: 21027
          protocol: UDP
        volumeMounts:
        - name: sync
          mountPath: /var/syncthing
      volumes:
      - name: sync
        persistentVolumeClaim:
          claimName: syncthing-data
