apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  type: ClusterIP
  ports:
  - port: 5432
    name: tcp-postgres
    protocol: TCP

