apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

transformers:
  - transform-nextcloud-image-tags.yaml
  - transform-nextcloud-labels.yaml

