---
# Sample persistent volume & claim using local-storage driver to provision
# a host path.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    # TODO: specify the host path to use as volume
    path: /media/data/nextcloud
  claimRef:
    namespace: default
    name: nextcloud-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                # TODO: change this to your node's hostname
                - my-node1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

