apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: redis
        image: "redis:alpine"
        imagePullPolicy: IfNotPresent
        command:
        - redis-server
        - "/etc/redis/redis.conf"
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/redis"
      volumes:
      - name: config
        configMap:
          name: redis
          items:
          - key: redis.conf
            path: redis.conf

